### ISSUE TITLE
Restructuring the repository

### ISSUE THREAD

**Issue by DanielSchuette** [PhilippSchuette/projecteuler#11]
@PhilippSchuette We should:
1. Update the description of the repo
2. Add some tags for languages, algorithms and so on
3. Rename the solution files in `./code` (or `py_src`) from `problem1.py` to `problem001.py` and so on (this includes modifying the imports in `test.py` and `problem7.py`)
4. Update the `README.md`, especially the table:
        1. Add language fields
        2. Add runtime fields for all the languages and solutions
        3. Actually time the solutions (should be done on @PhilippSchuette machine and not on a laptop)

**Comment by PhilippSchuette** [comment]
Also, the next commit should include the deletion of the now outdated folder /code!

**Comment by PhilippSchuette** [comment]
@DanielSchuette - what additional restructuring were you thinking of? Maybe you can take a final look and close this issue afterwards.

**Comment by PhilippSchuette** [comment]
Also, someone should include the runtime results in the newly created column of the README.

**Comment by DanielSchuette** [comment]
I timed the Python solutions and except for two solutions, everything looks good. I also added Go solutions 1 through 10, but I have to clean things up a bit and actually time them. I will open a new issue for that and close this one!
