### ISSUE TITLE
Unit test implementation for C++

### ISSUE THREAD

**Issue by DanielSchuette** [PhilippSchuette/projecteuler#14]
Which framework should we use for C++ unit tests? Looks like [CodeCov](https://docs.codecov.io/docs) offers multiple options for [C++](https://docs.codecov.io/docs/supported-languages). If @T-Rex96 you decide which one we should pick, I will go ahead and include the C++ build in our `.travis.yml`. Same thing for JS, Go and C, but for those languages I actually know how to do testing/CI so I'll take care of that as soon as possible. I think I only need help with C++, really.

**Comment by T-Rex96** [comment]
I think [Catch2](https://github.com/catchorg/Catch2) is the most popular one at the moment, [this](https://github.com/fkromer/catch_cmake_coverage) looks like an example for how to set it up

**Comment by DanielSchuette** [comment]
Good point. I will take a look at it and let you know if I have any problems integrating it into our pipeline. If I manage to streamline the build and automate testing for `C++`, I will put a note into the `README.md` for future reference and close this issue. If not, I'll post any issues here.
