### ISSUE TITLE
Unit Test Implementation for C

### ISSUE THREAD

**Issue by PhilippSchuette** [PhilippSchuette/projecteuler#18]
I have started solving the first few problems in C. I will probably solve some more of the early problems (1 - 15), but only those, that I have not solved with Python already.

More importantly, we will need unit tests for the C programs. Any suggestions are welcome!

**Comment by DanielSchuette** [comment]
I'll take a look at the CodeCov and Travis documentation pages. They most likely suggest some framework/tool that reports code coverage etc. It's probably a good idea to create a Makefile that compiles all solutions at once and cleans up afterwards, anyway.

**Comment by DanielSchuette** [comment]
I had to update the `.gitignore` to push a Makefile for our C code. We can still ignore the C++ Makefile if that's better (for now I pushed it by accident though).

**Comment by T-Rex96** [comment]
Yeah, the C++ Makefile should still be ignored since it's automatically generated by CMake

**Comment by DanielSchuette** [comment]
Builds and tests are now passing for C. With the current setup, we don't really test the solutions though, we just test the successful execution of all possible execution paths in the C files. That means we should implement some assertions in a separate c file that check the expected results of any functions in the `problem.c` files. I can take care of that (different issue though).

**Comment by DanielSchuette** [comment]
Ok I'll remove the file from the repo and add it to the `.gitignore` again (absolute path though since we need the C Makefile for Travis).
