### ISSUE TITLE
Add Go, Rust and C++ to CI Pipeline

### ISSUE THREAD

**Issue by DanielSchuette** [PhilippSchuette/projecteuler#21]
@DanielSchuette makes our repository nice and clean with a complete, basic CI + automated testing pipeline for all languages (@T-Rex96 I might have to ask questions related to `C++` though).

**Comment by T-Rex96** [comment]
I added a C++ build to the `.travis.yml` file, seems to work fine

**Comment by DanielSchuette** [comment]
We need to run `gcov`, if we want to report code coverage, too. Or at least that is the tool that our `C` build uses. `C++` documentation can be found [here](https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_gcov). I actually tried to add this, but I have a `FIXME` in `cpp_src/get_code_cov` that I don't really know how to handle. We need to compile with `--coverage`, but the `C++` build with `cmake` is something I don't really want to manipulate. Is this easy for you to add?

**Comment by T-Rex96** [comment]
Doesn't look that straightforward, I'll take a look over the weekend

**Comment by T-Rex96** [comment]
Alright, looks like I figured it out! I only need to somehow tell gcov to ignore the main() functions, [looks like one has to use lcov instead of gcov in that case](https://stackoverflow.com/questions/3555083/how-do-i-tell-gcov-to-ignore-un-hittable-lines-of-c-code)

**Comment by DanielSchuette** [comment]
Do you think that's worth digging into? Another option would be to only report test coverage for `tests.cpp` and not for the problem solutions (assuming that all functions in the problem solutions are covered by unit tests anyway). With Travis, we always know whether the build succeeds so I would probably try to ignore the `problem*.cpp` files for now. Your call.

**Comment by T-Rex96** [comment]
Got it to work :) Check out https://github.com/PhilippSchuette/projecteuler/commit/17737c8b321fd76a98ed05f08cc90246736eef4a

**Comment by DanielSchuette** [comment]
Awesome!
