### ISSUE TITLE
Fast `is_prime` function to speed up problems 7 and 10 in Python

### ISSUE THREAD

**Issue by DanielSchuette** [PhilippSchuette/projecteuler#9]
Can we implement `is_prime` from problem 3 in a faster way? I imported it as a helper function in problem 7 and I guess there will be many more future use cases for a prime number calculating function. We could re-name the current `is_prime` to `is_prime_old` and re-implement `is_prime` for faster prime number calculation across problems if you guys have any idea how to achieve that.

**Comment by T-Rex96** [comment]
[This test](https://en.wikipedia.org/wiki/Baillie%E2%80%93PSW_primality_test) seems to be quite popular and is deterministic for 64 bit numbers. Maybe a job for @PhilippSchuette?

**Comment by DanielSchuette** [comment]
@PhilippSchuette - do it!

**Comment by PhilippSchuette** [comment]
I'll have a quick look at it. If any other utilities like this come up, they should probably be stored in a separate util.py file. If I manage to implement the above idea, I will create it. Remember to use (or create) that one in the future, though!

**Comment by T-Rex96** [comment]
I guess in the meantime we could use https://docs.sympy.org/latest/modules/ntheory.html#sympy.ntheory.primetest.isprime for Python. This speeds up problem 7 by almost two orders of magnitude on my laptop.

**Comment by DanielSchuette** [comment]
Good idea. I pinned this issue and I will try to follow your suggestion. `problem010.py` is awfully slow, too.
